/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iot;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ATIF ADIB
 */
public class SenDataView extends javax.swing.JFrame {
    public static String txt;
    public static javax.swing.JLabel t1;
    /**
     * Creates new form SenDataView
     */
    public SenDataView() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabdata = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("DATA");

        tabdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DATA1", "DATA2", "DATA3", "AQUIRE-TIME"
            }
        ));
        jScrollPane1.setViewportView(tabdata);

        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("SENSOR-ID, SYSTEM-ID");

        t2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        t2.setText("-");

        jButton2.setText("CLICK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(71, 71, 71)
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(t2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //use txt while writing the queries;
//System.out.println(txt+"print");
       IOT obj=new IOT();
       SenDataView ob=new SenDataView();
       ob.setVisible(false);
       obj.startmenu();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          t2.setText(txt);
          DefaultTableModel ob=(DefaultTableModel) tabdata.getModel();
          String[] x=txt.split(",");
          
          int a=Integer.valueOf(x[0]);int b=Integer.valueOf(x[1]);
          String count="select count(*) from sendata where sysID=? and senID=?;";
          IOT obj=new IOT();
          Connection con=null;
          String c="";
          try{
              Class.forName(obj.driver).newInstance();
              con=DriverManager.getConnection(obj.url,obj.user,obj.pass);
              PreparedStatement stmt=con.prepareStatement(count);
              stmt.setInt(1, a);
              stmt.setInt(2,b);
              ResultSet rs=stmt.executeQuery();
              while(rs.next()){
                  c=rs.getString(1);
              }
              int cn=Integer.valueOf(c);
              ob.setRowCount(cn);
              t2.setText(txt+" ,returning:"+cn+" rows");
              con.close();
          }
          catch(SQLException e){
              System.out.println(e);
              System.out.println("here1");
          }
          catch(Exception e){
              System.out.println(e);
          }
          int i=0;
          try{
              String query="select data1,data2,data3,aquiretime from sendata where sysID=? and senID=?;";
              Class.forName(obj.driver).newInstance();
              con=DriverManager.getConnection(obj.url,obj.user,obj.pass);
              PreparedStatement stmt1=con.prepareStatement(query);
              stmt1.setInt(1, a);
              stmt1.setInt(2,b);
              ResultSet rs1=stmt1.executeQuery();
              while(rs1.next()){
                  String dat1=rs1.getString(1);
                  
                  String dat2=rs1.getString(2);
                  
                  String dat3=rs1.getString(3);
                  
                  String aqr=rs1.getString(4);
                  ob.setValueAt(dat1, i, 0);
                  ob.setValueAt(dat2, i, 1);
                  ob.setValueAt(dat3, i, 2);
                  ob.setValueAt(aqr, i, 3);
                  i++;
              }
              con.close();
          }
          catch(SQLException e){
              System.out.println(e);
              
              System.out.println("here2");
          }
          catch(Exception e){
              System.out.println(e);
          }
          
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SenDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SenDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SenDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SenDataView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SenDataView().setVisible(true);
            }
        });
        txt=SensorSelect.a;
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel t2;
    private javax.swing.JTable tabdata;
    // End of variables declaration//GEN-END:variables
}
